danielbuechele/goofy

server/src/fb.css
This fixes the *ugly* “New Message” button in collapsed mode ( #9 )
=> Fix for button in collapsed mode

Goofy/Base.lproj/MainMenu.xib
I think using the continuous present in this instance sounds more natural.
=> Typo fix in long wait string

server/gulpfile.js
Lets developers to automatically build on save
=> Add gulp-watch

server/src/fb.js
Keyboard shortcut for creating new message.
=> added Command+N for new message

server/src/fb.css
Ok - I can actually build it now and have made the selectable section more strict.
=> Made select CSS cover the correct sections.

server/src/fb.js
Haven't been able to test in the app itself (I get a load of build errors when I try and run in Xcode), but pasting the new code into the Safari console works fine.
=> Support drag and drop image uploads

server/src/fb.js
Fix from @blakeembrey in #49. Fixes #49, fixes #31.
=> Fix system beep on first input keypress

server/src/fb.js
=> Don't steal focus from other inputs on keypress

server/src/fb.js
ID is dynamically generated, will (and has) changed.
=> Get file upload input without using ID

server/src/fb.js
Changed smile emoticon to be same as is in Mac Os X messages for `:)`.
=> Changed smile emoticon

Goofy/NotificationScriptMessageHandler.swift, server/src/fb.js
=> Display user picture in new message notification

Goofy/NotificationScriptMessageHandler.swift
Adding rounded corners to NSImage, for NSUserNotification pictures. I feel that a round mask looks more desirable than the default rectangular image. Attached a screenshot of what it could look like.
=> Adding rounded corners to notification pictures

Goofy.xcodeproj/project.pbxproj, Goofy/Info.plist
Removes user-specific details from the build process and ensuring that the build phases work on a fresh clone without changing any settings. That makes it easier for others besides the maintainer to contribute or build from source.
=> Improve the build process

Goofy/Base.lproj/MainMenu.xib
Lowercase letters in "conversations" and "updates" aren't consistent with the OS X convention.
=> Capitalize Menu Items

Goofy.xcodeproj/project.pbxproj, Goofy/Info.plist, server/src/fb.js
=> Self notification bug

README.md, server/gulpfile.js, server/src/fb.css, server/src/fb.js
* Made Styling of CSS Consistent with the rest of the file
* Made Styling of JS Consistent with the rest of the file
* Added Links to `README.md`
=> Changed Styling of CSS, JS, and README

Goofy/AppDelegate.swift
Fix for https://github.com/danielbuechele/goofy/issues/266
=> Fixed video playback

Goofy/AppDelegate.swift, Goofy/Base.lproj/MainMenu.xib, Goofy/Info.plist, Goofy/MenuHandler.swift, Goofy/NotificationScriptMessageHandler.swift
Hi,
I wrote some lines in order to enable the menu bar bahavior. Here is how it works:
- If the toggle menubar icon is set on then the dock and menu bar app are hidden. Left click on the menubar icon show / hide the app and right click show the statusItem menu (to change deactivate the menu bar behavior or to quit the app)
- If the toggle menubar icon is set to off then goofy runs as active app
Hope you will like it
I wish you a very happy festive season!
=> Enable Menu bar app

README.md
Resolves https://github.com/danielbuechele/goofy/issues/324.
=> Update the readme with new build instructions

.gitignore, app/src/assets/fb.js, package-lock.json
It includes the perfomance fix and the self notification bug fix.
https://github.com/danielbuechele/goofy-core/pull/11
https://github.com/danielbuechele/goofy-core/pull/12
=> Fix bug danielbuechele/goofy#369 related to self notification issue

app/src/assets/fb.css, app/src/assets/fb.js
=> Fix New Conversation menu option not working

app/src/menu.js, package-lock.json
=> Add zoom options to the View menu
