server/package.json, server/src/fb.css
Hi, I couldn't build the app to test this (xcode noob) but I have added CSS which - in the browser version of messenger - makes only the comments section selectable. Let me know if it doesn't work.
Basically, I figured this looked a bit ugly and makes it feel non-native:
RE building the app I get this error 
but I've never developed mac apps so *shrugs*..
=> Fixed package.json, made only conversation selectable

server/src/fb.css
Limits the hiding of names to the sidebar, and not the results of the
“New Message” menu
=> Show name of results in collapsed mode

server/src/fb.js
Previous implementation fired the key event on the input successfully,
so the letter you pressed made it into the input - but it didn't then
focus the input, so you couldn't keep typing.
It also only checked that the spans containing text didn't exist -
meaning once there's a single character in the input, the code stops
running. Instead, check if the input's focused, and focus after firing
the event.
=> Fix text input focusing on keypress

Goofy/AppDelegate.swift
Messenger.com updated to navigate to "https://www.messenger.com/" as part of loading, which wasn't allowed in the list of whitelisted URLs. I've switched to a blacklist instead — the only thing I've seen that shouldn't open in app is the external link page (`l.php`).
I've also added support for logging in with verifications enabled.
=> Fix Messenger.com opening in browser on launch

Goofy/Info.plist, update_feed.xml
Puts the XML feed in the repository instead of on a separate website (now can just be edited with a commit like anything else) and updates the app to point to the new URL.
=> Switches Sparkle update XML feed to Github hosting

Goofy/AppDelegate.swift, Goofy/Base.lproj/MainMenu.xib, server/src/fb.js
Safari doesn't implement DataTransfer.items, so there's no way to
extract image data (i.e. a screenshot copied to the clipboard) in
Javascript. You can get copied files, but not data. Capture the paste
in Swift and then forward on the image data to the webview.
Currently supports pasting image data (and forwards on text), but
pasting an image file doesn't work — when you try to paste a file it sends the icon instead. My Swift-fu isn't that great, so someone else will need to fix that.
=> Add image pasting functionality

Goofy/MenuHandler.swift
Only `png`, `jpg` and `gif` was supported but sometimes jpg files have `jpeg` extension
=> Add support for sending ".jpeg" image attachments

Goofy/AppDelegate.swift
In the case that this is a link that has been formatted to l.messenger.com (IE, facebook warns us that we are leaving facebook through a link), extract the URL and direct the user to it directly instead of the 2 step facebook passthrough process
For issue #150
=> Bypassing Facebook passthrough link for links which are outside of the Facebook domain

Goofy/NotificationScriptMessageHandler.swift
Solves #175 - occurs when a potentially-nil value is force-unwrapped and passed to roundCorners.
=> Unwrap picture with if-let before rounding corners

server/src/fb.js
Replaced :( with [😞](http://emojipedia.org/disappointed-face/). 😞 is a better option and is what Facebook uses in their iOS apps.
=> Changed frown emoji

Goofy/AppDelegate.swift, Goofy/Base.lproj/MainMenu.xib, Goofy/NotificationScriptMessageHandler.swift
Hi Daniel,
I took the pre-existing work and completed the integration for the Status Bar / Menu Bar icon feature.
The default behaviour now is to display it. Visibility can be toggled via the previously disabled main menu entry (renamed to "Toggle Menubar Icon"). The configuration value is stored in NSUserDefaults "showStatusItem". This is used as the single source of truth for configuration of this feature, as checking of NSStatusbarItem visibility would require hacks.
Looking forward to your thoughts, merry christmas from Berlin,
S
=> Completed integration of Menubar Icon feature

server/src/fb.js
Also includes Turkish support. Other languages can be added to the
YOU_KEYWORDS object whenever requested or discovered. Based
on the discussion we had on #205.
The idea and base of the code is from @joallard
=> Add a system for langugage-specific replacements of "You: "

Goofy/NotificationScriptMessageHandler.swift
If the reply contains multiple lines, the "\n" causes JS to be evaluated breaken into multiple lines, causing it to silently fail. This fixes it by escaping the newline.
This might be a fix to #240.
=> Fix replying in notification sometimes not working

Goofy/AppDelegate.swift, Goofy/Info.plist
Allows Goofy to successfully run as a login item.
Judging by the console messages, Goofy was trying to acquire focus before actually being focusable. Given that the window is focused if launched anyways, this preserves the old behavior while addressing #235 and #162.
P.S. I am totally new to OS X development, so I'm not sure why Xcode changed CFBundleVersion. Please let me know if I've done something wrong 🙇
=> fixes #235, #162

Goofy/Info.plist, Goofy/TitleLabel.swift, server/src/fb.css
CSS and TitleLabel changed to use system font (San Francisco).
Methods for [CSS](http://furbo.org/2015/07/09/i-left-my-system-fonts-in-san-francisco/) and [TitleLabel](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSFont_Class/index.html#//apple_ref/occ/clm/NSFont/systemFontOfSize:) linked.
=> fixes #261

Goofy/AppDelegate.swift
Messenger.com now wraps http links with the http://l.messenger.com prefix (instead of using https for all links). The regex handling outbound links has been changed to match this.
=> Fix crash when opening HTTP links

README.md
OS X was renamed to macOS (Sierra) in the latest version :)
=> Update README to reference macOS instead of OS X

README.md
When searching for commits or trying to understand code I kept searching for this repo. A link in the readme helps a lot and clears up the relationship.
=> Added link to goofy-core submodule

app/src/assets/fb.css, app/src/assets/fb.js
_36ic was changed to _3lz9, making the settings cog appear.
It also made the query selectors unable to find the button when opening the preferences, so this issue is also fixed.
=> updated class naming

app/src/assets/fb.css, app/src/assets/fb.js
- Remove Settings button from menu bar
- Also fixed settings shortcut (cmd-,) not working
- Consequently also fixes the “Gear Menus” on conversations
This fixes #410 and also #343
=> Fix Settings button (UI and shortcut)

app/package-lock.json
potential missing versioning.
I noticed in release v3.3.5, the version was updated in the file 'app/package-lock.json' but was not done so for version v3.4.0. went ahead and updated and PRing.
=> Update version 3.4.0

app/src/fb.js
Because ```en-US``` is the only supported language by ```electron-spell-check-provider``` at present and spell checking of another language slowing down the app, I made the condition for app language – ```app.getLocale()```.
Spell checking available only for ```en-US```.
=> Disable spell checking for non 'en-US' language – based on app locale

app/src/assets/fb.css
Upon further inspection, I also added 
--nav-bar-padding: 28px;
It has effect on the following: [image](https://i.imgur.com/n765u70.png)
Brings the contact elements in line with the other elements like call, video call and info.
=> fixed left column being overlayed by window actions
